### PR TITLE
UI enhancement for SignIn, SignUp,auth/signin/index.html and auth/signup/index.html pages

### PR DESCRIPTION
**Pull request by faiz66388**
Add hover effects to input fields, shadows to borders, and title. Also, implemented password visibility features.

SignIn:
image
SignUp: 
image
auth/signin/index.html :
image
auth/signup/index.html :
image
Closes #23

### CODE REVIEW

**Comment by faiz66388** [comment]
@ChandelAnish Could you check if this works for you?

**Review by ChandelAnish — COMMENTED** [review]
-->our website fallows purple-white color theme , so make button and heading color purple instead of blue
color similar to this:
image

do this changes and I'll merge your PR

**Comment by faiz66388** [comment]
I have changed color as you told. Could you check, if it's fine?

**Comment by faiz66388** [comment]
@ChandelAnish Could you please check this PR, as I have changed color as you suggested?

**Pull request closed without merging**
