### PR TITLE
Create Contributing.md

### PR DESCRIPTION
**Pull request by rajatsinghal02**

### CODE REVIEW

**Review by ChandelAnish — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
No labels and no issue number mentioned @rajatsinghal02

**Comment by AKSHITHA-CHILUKA** [comment]
Yeah you mention in the description first then let him assign the labels

**Comment by AKSHITHA-CHILUKA** [comment]
provide your issue no

**Comment by AKSHITHA-CHILUKA** [comment]
@ChandelAnish please add the labels

**Pull request merged**
