### PR TITLE
feature: hash password login implememnted

### PR DESCRIPTION
**Pull request by Mr-jas91**
fix: #13 
This pull request introduces a new feature to enhance user profile security by hashing passwords using the bcrypt algorithm. By implementing bcrypt, we ensure that user passwords are securely stored, making it more difficult for unauthorized access in the event of a data breach.

**Password Hashing**: Implemented bcrypt to hash user passwords during registration and update processes.
**Validation**: Added validation to ensure passwords meet complexity requirements before hashing.
**User Model Update**: Updated the user model to store the hashed password instead of plain text.
**Authentication Update**: Modified the login process to compare the hashed password with the provided input.
**Tests**: Added unit tests to verify that passwords are correctly hashed and validated during user authentication.

Screenshot (32)
Screenshot (33)

### CODE REVIEW

**Review by ChandelAnish — COMMENTED** [review]
currently after sign up, user need to pass the hash password inorder to login which he doesn't know
-->you need to hash the password input by the user during login and then  match that hashed password with hashed password stored in the DB

image

**Comment by Mr-jas91** [comment]
You are login using your old password. And your old password is not hashed when you are login then it hash first, then compare. But your password is stored in plane text and it is match with your hash password and plane text. 

Your can test like this
Create a new account then login.

**Review by Mr-jas91 — COMMENTED** [review]
Before login compare the hash password with stored password is resolved.

**Comment by Mr-jas91** [comment]
I think, I fix the issue but issue is not closed. Can I know, any other issue still occurs.

**Review by ChandelAnish — COMMENTED** [review]
PR on the dev branch

**Comment by CogitoKunal** [comment]
Your Issue has Conflicts with files So resolve it first

**Pull request closed without merging**
