### PR TITLE
Added ProgressBar | Issue #69

### PR DESCRIPTION
**Pull request by Shariq2003**
I have successfully added a ProgressBar in the WebApp.

Completed #69

### CODE REVIEW

**Comment by Shariq2003** [comment]
@CogitoKunal sir, please review and merge this

**Comment by CogitoKunal** [comment]
Your Contribution is accepted

**Comment by CogitoKunal** [comment]
Hey Please Solve Signin not Working

**Comment by Shariq2003** [comment]
@CogitoKunal you haven't added gssoc-ext labels and also label of level.

**Comment by Shariq2003** [comment]
@MastanSayyad sir, sorry for disturbing again, but you just have to add labels, pleaseeeeeeee.

**Comment by Shariq2003** [comment]
@CogitoKunal sir you haven't added labels

**Pull request merged**
