### PR TITLE
Sign-In Page Updates: Bug Fixes and Improvements!!

### PR DESCRIPTION
**Pull request by Ishratnoori**
- Fixed the issue with the sign-in page not handling user credentials properly.
- Improved UI/UX for the sign-in form.
- Added input validation to prevent empty fields.
- Refactored the authentication logic for better performance.

### CODE REVIEW

**Comment by Ishratnoori** [comment]
Hi @CogitoKunal @ChandelAnish , just wanted to check in to see if you've had a chance to review this PR. Let me know if you need any additional information or changes. Thanks!

**Comment by CogitoKunal** [comment]
we will check it within 2 days

**Review by CogitoKunal — APPROVED** [review]

**Comment by Mr-jas91** [comment]
@CogitoKunal 
she removed root from the html file at client folder, which create error. kindly check it.

**Comment by CogitoKunal** [comment]
ya you are right just correct this issuw

**Comment by Mr-jas91** [comment]
I have created new pull request and close old pull request. Kindly merge new. 
> ya you are right just correct this issue

**Comment by Mr-jas91** [comment]
I will correct her mistake. Give me 1 to 2 days. 
> ya you are right just correct this issue

**Comment by CogitoKunal** [comment]
okkk

**Pull request merged**
