### PR TITLE
Enhancement : Improved Layout of Sign-Up Page and Added Sign-In Link for Existing Users.

### PR DESCRIPTION
**Pull request by salonijoshi1980**
# **Description :**
-  This update refines the layout of the sign-up page to enhance readability and accessibility, creating a more intuitive experience for new users.
-  It also introduces a link to the sign-in page for users who already have an account, allowing easier navigation between registration and login processes.

# **Changes Made :**
**Overall Layout Redesign :**
1. Adjusted the spacing, alignment, and positioning of the input fields (username, email, and password) to create a cleaner, more organized look.
2. Updated padding and margin settings to provide balanced spacing, improving the visual structure and readability.
3. Grouped input fields with clear labels and enhanced visual hierarchy to guide users through the sign-up steps.

**Sign-In Page Link Addition :**
1. Added a link below the sign-up form with the text “Already have an account? Sign In.”
2. Styled this link in a secondary color to visually separate it from primary actions, ensuring it's noticeable without overwhelming the main focus of the page.
3. Included a hover effect to improve accessibility and clarity for users.

# **Rationale**
1. The layout changes aim to create a streamlined, easy-to-follow design that guides users through the sign-up process without distraction. 
2. By enhancing the visual appeal and simplifying the structure, we reduce cognitive load and make the page more approachable, which is essential for onboarding new users effectively. 
3. Adding the “Sign In” link addresses a common user need, allowing those who already have an account to quickly navigate to the login page, improving their overall experience and reducing frustration.

# **Impact on User Experience**
**Enhanced Visual and Functional Usability :**
1. A more polished layout helps users focus on each field and action, reducing the likelihood of errors during sign-up. This improved structure makes the page appear more professional and engaging.

**Efficient Navigation for Returning Users:**
1. The sign-in link serves as a clear, convenient option for users who may have previously registered but ended up on the sign-up page. 
2. This change streamlines their experience, reducing time spent searching for login options and making the sign-up page more versatile.

**Improved User Retention:**
1. Simplified navigation and an aesthetically appealing layout enhance the onboarding experience, increasing the likelihood of successful registrations and reducing bounce rates. The design change supports both new and returning users, encouraging them to stay engaged with the site.

- **This pull request** ultimately enhances the accessibility and usability of the sign-up page, providing a smoother, more intuitive experience for all users.

# 📄 **Type of Change :**
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 **Screenshots/GIFs (if any) :**
- **Before issue solved :** 

Screenshot 2024-11-04 120900

- **After issue solved :**

Screenshot 2024-11-04 135924

Screenshot 2024-11-04 135944

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.

### CODE REVIEW

**Comment by salonijoshi1980** [comment]
@CogitoKunal assigned me with this and give labels of **Gssoc extd and level 3**, In index.html main file the overall html code was comment out but i removed it .

**Comment by salonijoshi1980** [comment]
@CogitoKunal  i saw  in  sign-in page the layout and design is not completed so ,if u want i'll style it.

**Comment by salonijoshi1980** [comment]
and hmm i only move and change  index.html to index1.html of sign-up page in sign-in , because it give issue in linking and it create another space and folder

**Comment by CogitoKunal** [comment]
@salonijoshi1980 You are Assigned, All the Best

**Comment by salonijoshi1980** [comment]
@CogitoKunal hey merged it pls.. then i claimed my points otherwise it doesn't worth it!

**Comment by CogitoKunal** [comment]
@salonijoshi1980 your contribution has been successfully accepted

**Pull request merged**
