### PR TITLE
signin-signup form navigation

### PR DESCRIPTION
**Pull request by Sureshwebdeveloper**
signup and signup navigation added user now toggle.

### CODE REVIEW

**Comment by ChandelAnish** [comment]
share screenshots or screen recording to support your resolution

**Comment by Sureshwebdeveloper** [comment]
please add tag gssoc-ext hacktoberfest-accepted and also add a level of problem.


https://github.com/user-attachments/assets/629c118b-03c2-48a8-ac93-c71874ff0ae4

**Comment by Sureshwebdeveloper** [comment]
**This close**
 Signup page login page no toggle button for switch signup and login text error in login page #15

**Comment by Sureshwebdeveloper** [comment]
@ChandelAnish please check above attached document

**Comment by CogitoKunal** [comment]
Your Branch has Conflicts So Resolve Conflicts otherwise it will not be Merged

**Comment by Sureshwebdeveloper** [comment]
> Your Branch has Conflicts So Resolve Conflicts otherwise it will not be Merged

Thanks I will resolve as soon as possible

**Comment by Sureshwebdeveloper** [comment]
> signup and signup navigation added user now toggle.

please assign to me unfortunately i will discord commits

**Comment by CogitoKunal** [comment]
There was conflict with some branch did you resolved that issue?

**Pull request closed without merging**
